### ISSUE TITLE
connect_string not found

### ISSUE THREAD

**Issue by dmiego** [tango-controls-hdbpp/libhdbpp-timescale#2]
Hello.
I've installed timescale-based library and trying to start EventSubscriber.
With -v5 option I have output message:
> FATAL sys/tools/hdb++es-srv PushThreadShared: error connecting DB: Configuration parsing error: mandatory configuration parameter: connect_string not found

I've also added desc and origin error output:
> Configuration parsing error: mandatory configuration parameter: connect_string not found HdbppTimescaleDb.cpp:getConfigParam:78

There is a LibConfiguration property in ES server

> libname=libhdb++timescale.so
host=localhost
port=5432
dbname=hdb
user=hdb_event_sub
password=hdbpp

DB and users was created from .sql files.

Is the way of configuring changed? How can I fix it?

Debian 10, Tango 9.3.4-rc1, everything else is latest version cloned from github.

**Comment by chedburgh** [comment]
Yes, this is not obvious since its not documented! 

A new LibConfiguration is required as follows:

connect_string=user=USER password=PASSWORD host=HOSTNAME port=PORT dbname=hdb
logging_level=error
log_file=false
log_console=false
libname=libhdb++timescale.so

Take a look at the code in HdbppTimescaleDb.cpp for some details on how to switch on various logging systems. I will keep this ticket open while I update the documentation.

Thanks for the question!

**Comment by dmiego** [comment]
Thanks, that worked.
Now I have problem with Configuration Manager.
I've created new issue there.

**Comment by chedburgh** [comment]
This is now addresses in the v0.10.0 branch which is being prepared for release.

**Comment by chedburgh** [comment]
Fixed in [#5]
